"""add_email_metadata_flags

Revision ID: 34dd9737e200
Revises: fd6e2b98ae43
Create Date: 2025-11-08 11:56:49.319527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34dd9737e200'
down_revision: Union[str, Sequence[str], None] = 'fd6e2b98ae43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('is_starred', sa.Boolean(), nullable=True))
    op.add_column('emails', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('emails', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'is_deleted')
    op.drop_column('emails', 'is_archived')
    op.drop_column('emails', 'is_starred')
    # ### end Alembic commands ###
