"""add_user_profile_fields

Revision ID: 7625a93b31b9
Revises: 1ac97efbf7e0
Create Date: 2025-11-08 17:38:36.580886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7625a93b31b9'
down_revision: Union[str, Sequence[str], None] = '1ac97efbf7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('expertise', sa.String(), nullable=True))
    op.add_column('users', sa.Column('looking_for', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('twitter_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('calendly_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'calendly_url')
    op.drop_column('users', 'website_url')
    op.drop_column('users', 'twitter_url')
    op.drop_column('users', 'looking_for')
    op.drop_column('users', 'expertise')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'industry')
    op.drop_column('users', 'location')
    op.drop_column('users', 'company')
    op.drop_column('users', 'job_title')
    # ### end Alembic commands ###
