"""add_username_and_threading_fields

Revision ID: c4921b652f50
Revises: 34dd9737e200
Create Date: 2025-11-08 14:07:39.415510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4921b652f50'
down_revision: Union[str, Sequence[str], None] = '34dd9737e200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add email threading and payment fields
    op.add_column('emails', sa.Column('message_id', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('in_reply_to', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('references', sa.Text(), nullable=True))
    op.add_column('emails', sa.Column('payment_required', sa.Boolean(), nullable=True))
    op.add_column('emails', sa.Column('payment_completed', sa.Boolean(), nullable=True))
    op.add_column('emails', sa.Column('payment_amount', sa.Float(), nullable=True))
    op.add_column('emails', sa.Column('payment_id', sa.String(), nullable=True))
    
    # Set default values for payment fields
    op.execute("UPDATE emails SET payment_required = 0 WHERE payment_required IS NULL")
    op.execute("UPDATE emails SET payment_completed = 0 WHERE payment_completed IS NULL")
    
    op.create_index(op.f('ix_emails_in_reply_to'), 'emails', ['in_reply_to'], unique=False)
    op.create_index(op.f('ix_emails_message_id'), 'emails', ['message_id'], unique=True)
    
    # Add username field as nullable first
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    
    # Generate usernames for existing users based on their email (before @)
    # This is a temporary solution - users should update their usernames
    op.execute("""
        UPDATE users 
        SET username = LOWER(SUBSTR(email, 1, INSTR(email, '@') - 1))
        WHERE username IS NULL
    """)
    
    # Make username NOT NULL after populating it
    # Note: SQLite doesn't support ALTER COLUMN, so we need to recreate the table
    # For now, we'll leave it as nullable and enforce in the app layer
    # In production, you'd want to recreate the table with proper constraints
    
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_emails_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_in_reply_to'), table_name='emails')
    op.drop_column('emails', 'payment_id')
    op.drop_column('emails', 'payment_amount')
    op.drop_column('emails', 'payment_completed')
    op.drop_column('emails', 'payment_required')
    op.drop_column('emails', 'references')
    op.drop_column('emails', 'in_reply_to')
    op.drop_column('emails', 'message_id')
    # ### end Alembic commands ###
