"""initial_migration

Revision ID: f994b87b6275
Revises: 
Create Date: 2025-11-07 22:29:46.080178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f994b87b6275'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('linkedin_state', sa.String(), nullable=False),
    sa.Column('linkedin_code', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_state')
    )
    op.create_index(op.f('ix_linkedin_verifications_id'), 'linkedin_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_linkedin_verifications_user_id'), 'linkedin_verifications', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('linkedin_id', sa.String(), nullable=True),
    sa.Column('linkedin_profile_url', sa.String(), nullable=True),
    sa.Column('linkedin_verified', sa.Boolean(), nullable=True),
    sa.Column('linkedin_verification_status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', name='verificationstatus'), nullable=True),
    sa.Column('price_limit', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_linkedin_verifications_user_id'), table_name='linkedin_verifications')
    op.drop_index(op.f('ix_linkedin_verifications_id'), table_name='linkedin_verifications')
    op.drop_table('linkedin_verifications')
    # ### end Alembic commands ###
